### ISSUE TITLE
[Addition] Additional info and correction about stations

### ISSUE THREAD

**Issue by fkrisi11** [VRLabs/VRCSchool#4]
I have done some testing, and based on that, I'd like to provide some more info about stations, to this page: [VRC School | Stations](http://vrc.school/docs/Other/Stations)

### The number of stations on an avatar
<hr>
The maximum number of stations that you can add to an avatar, is 6.
Any chair, after the 6th one that is found on the avatar, can not be used in the game.
The chair order is based on the hierarchy. So chairs will be made available from the top of the hierarchy to the bottom of it.
If Chair 7 is next to Chair 6 (below it), then Chair 6 will still be active, but Chair 7 will not be.

This is the hierarchy that I have used for the test:
![image](https://github.com/VRLabs/VRCSchool/assets/26310365/cc6df8dc-8104-4c4f-8e24-de6d42a68681)
### Maximum allowed distance between the Enty and Exit points
<hr>
Another additional info is that the Entry point of the station must be within 2 meters of the Exit point, or else the station will not work in the game.<br>
I tested a distance of 2.01 meters in game, and the station was not active because of this.<br>
I also tested a distance of 2.0001 meters in game, and the results are the same. The station is also not active because of this.<br>
<br>
Also, another interesting point is that if you exceed the distance limit between the Entry and Exit points, but the station would have been active otherwise, as it does not go over the avatar station number limit, it will still count towards it, despite not being active.
<br>
So if we look at the previous screenshot that I posted, and I set the Entry and Exit points of Chair 1 too far from each other, then the only active stations will be:

- Chair 2
- Chair 3
- Chair 4
- Chair 5
- Chair 6

Chair 7 will not be active in this case, as Chair 1 failed the Entry-Exit distance test, and it counts as an active station.
<br><br>
### Overcoming the distance limitation
<hr>
It is also important to note, that if the Entry and Exit points are within 2 meters of each other, and they become active in the game, then you can use an animation to move them further from each other, by any means, and the station will still be functional.
<br><br>

### A correction about stations
<hr>
While it is not possible to toggle the station script itself, it is possible to turn off the object in the hierarchy, that the station script is on.<br>
If you disable the object in the hierarchy, that the station script is on, then anyone sitting in said station will fall off of it<br>
I think the caution note should state this instead ^<br>
But it should also warn people that stations should be fully enabled in their hierarchy on upload, or else they will not work in game.<br>
They can be turned off on frame 1 however.<br><br>
Turning off the collider that the station is using, makes the station unclickable for others, but it will not kick the person, who is sitting in it already.
<br><br>
(Not sure if this should be noted, but good info):<br>
And to solve the annoying issue where people can just sit in your stations, because they have custom animations disabled for you, the solution is to put the stations high up in the air, or down low under the floor.

<br><br>

### What if a station script has no collider?
<hr>
If the station script has no collider on the object the script is on, then VRChat adds a collider to it automatically<br>

<br><br>

### The wrong type of collider?
<hr>
If the station script has a collider that is not set to Is Trigger, the station will still work (Does the game set it to Is Trigger(?))

**Comment by fkrisi11** [comment]
One more addition:
People, who sit in stations, face forward, towards the blue arrow (Z axis), and face up towards the green arrow (Y axis)
This is important, when placing a station on an avi

**Comment by jellejurre** [comment]
Added, thanks!
